server:
  servlet:
    context-path: /ggcycling
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ggcycling?serverTimezone=GMT
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.spir.ggcycling.bean
